<?php

const DIRNAME_REPOSITORY = 'repository';
const DIRNAME_TEMPLATECACHE = 'templates';
const DIRNAME_CACHE = 'cache';
const DIRNAME_DOCROOT = 'web';
const DIRNAME_LOGS = 'logs';
const DIRNAME_TEXTCATS = 'textcats';
const DIRNAME_PAGES = 'pages';

define('PATH_BASEDIR', realpath(__DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'));
define('PATH_DOCROOT', PATH_BASEDIR.DIRECTORY_SEPARATOR.DIRNAME_DOCROOT);
define('PATH_REPOSITORY', PATH_BASEDIR.DIRECTORY_SEPARATOR.DIRNAME_REPOSITORY);
define('PATH_CACHE', PATH_REPOSITORY.DIRECTORY_SEPARATOR.DIRNAME_CACHE);
define('PATH_TEMPLATECACHE', PATH_CACHE.DIRECTORY_SEPARATOR.DIRNAME_TEMPLATECACHE);
define('PATH_LOGS', PATH_REPOSITORY.DIRECTORY_SEPARATOR.DIRNAME_LOGS);
define('PATH_TEXTCATS', PATH_REPOSITORY.DIRECTORY_SEPARATOR.DIRNAME_TEXTCATS);
define('PATH_PAGES', PATH_REPOSITORY.DIRECTORY_SEPARATOR.DIRNAME_PAGES);
