
# the url in localrelative is treated as relative from the base path of the installation
type: localrelative
url: repository

#type: localabsolute
#url: /var/www/html/somedirectory/repository

#type: guzzle
#url: https://username:password@www.haase-it.com/dummy_endpoint/repository
