
# the url in localrelative is treated as relative from the base path of the installation
type: localrelative
url: repository

#type: localabsolute
#url: /var/www/html/somedirectory/repository

#type: dav
#url: https://www.haase-it.com/dummy_endpoint/repository
#user: john_doe
#password: secret
